default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: my_password
      port: 5432
      dbname: analytics
      schema: public
      threads: 4
      database: licenses_db
      schema_directory: /home/user/chargemaps/app/dbt/models