# test docker containers
name: Tests

on:
  push:
     branches:
      - dev
      - master
      - docker_compose_postgre

  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - dev
      - master

jobs:

  all_tests:
    strategy:
      matrix:
        os:
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build base image
        run: docker build -f Dockerfile.base -t pipeline-base:latest .

      - name: Build pipeline image
        run: docker build -t pipeline:latest .

      - name: Test docker
        run: docker run --name pipeline-test -e MODE=test pipeline:latest

      - name: Display logs
        if: failure()
        run: |
          docker logs pipeline-test
          docker inspect pipeline-test

      - name: Clean up
        if: always()
        run: docker rm -f pipeline-test

  docker_compose:
    strategy:
      matrix:
        os:
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Verify Docker
      run: |
          docker --version
          docker compose version
    - name: check env vars
      run: docker compose config
    - name: Build pipeline
      run: docker compose build pipeline

    - name: Start database
      run: docker compose up -d db

    - name: Wait for database
      run: |
        until docker compose exec -T db pg_isready -U myuser -d licenses_db; do
        sleep 2
        done
    - name: Show running containers
      run: docker compose ps

    - name: Show logs on failure
      if: failure()
      run: docker compose logs

    - name: Tear down
      if: always()
      run: docker compose down -v

  docker_compose_dbt:
    strategy:
      matrix:
        os:
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Verify Docker
      run: |
          docker --version
          docker compose version
    - name: check env vars
      run: docker compose config

    - name: start db
      run: |
        docker compose up -d db
        until docker compose exec -T db pg_isready -U myuser -d licenses_db; do
          sleep 2
        done

    - name: build pipeline
      run: MODE=dbt-pipeline docker compose build pipeline

    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        version: "0.11.28"

    - name: Run dbt pipeline
      run: |
        MODE=dbt-pipeline docker compose run --rm pipeline

    - name: check data has been produced
      run: |

        uv venv --python 3.12
        source .venv/bin/activate
        uv pip install -r requirements.txt
        uv run python -m app.check_docker_db
        docker compose down -v


    - name: Start dbt tests
      run: |
        MODE=test-dbt docker compose build  pipeline
        docker compose up -d db
        docker compose run --rm pipeline test

    - name: Show running containers
      run: docker compose ps


    - name: use incremental_pipeline
      run: MODE=incremental_pipeline docker compose build incremental_pipeline

    - name: Show logs on failure
      if: failure()
      run: docker compose logs

    - name: Tear down
      if: always()
      run: docker compose down -v
